$(document).ready(function(){const flowersSlider=new Swiper('.flowers-slider',{loop:!0,slidesPerView:6,navigation:{nextEl:'.swiper-button-next',prevEl:'.swiper-button-prev',},breakpoints:{320:{slidesPerView:1,},480:{slidesPerView:3,},992:{slidesPerView:6,}}});const reviewsSlider=new Swiper('.reviews-slider',{loop:!0,slidesPerView:1,navigation:{nextEl:'.swiper-button-next',prevEl:'.swiper-button-prev',},});$("#review-1").on('click',function(){$.fancybox.open([{src:'./img/reviews/review-1.jpg',opts:{caption:'&nbsp;',thumb:'./img/reviews/review-1.jpg'}},{src:'./img/reviews/review-2.jpg',opts:{caption:'&nbsp;',thumb:'./img/reviews/review-2.jpg'}},{src:'./img/reviews/review-3.jpg',opts:{caption:'&nbsp;',thumb:'./img/reviews/review-3.jpg'}}],{loop:!0,thumbs:{autoStart:!0}})});$("#review-2").on('click',function(){$.fancybox.open([{src:'./img/reviews/review-2.jpg',opts:{caption:'&nbsp;',thumb:'./img/reviews/review-2.jpg'}},{src:'./img/reviews/review-3.jpg',opts:{caption:'&nbsp;',thumb:'./img/reviews/review-3.jpg'}},{src:'./img/reviews/review-1.jpg',opts:{caption:'&nbsp;',thumb:'./img/reviews/review-1.jpg'}}],{loop:!0,thumbs:{autoStart:!0}})});$("#review-3").on('click',function(){$.fancybox.open([{src:'./img/reviews/review-3.jpg',opts:{caption:'&nbsp;',thumb:'./img/reviews/review-3.jpg'}},{src:'./img/reviews/review-1.jpg',opts:{caption:'&nbsp;',thumb:'./img/reviews/review-1.jpg'}},{src:'./img/reviews/review-2.jpg',opts:{caption:'&nbsp;',thumb:'./img/reviews/review-2.jpg'}}],{loop:!0,thumbs:{autoStart:!0}})})});let buttonPlus1=document.getElementById("count-plus-1");let buttonMinus1=document.getElementById("count-minus-1");let inputCount1=document.getElementById("counter-input-1")
function getCount1(){return Number(inputCount1.value)}
buttonPlus1.addEventListener("click",function(){if(inputCount1.value<=14){inputCount1.value=getCount1()+Number("1")}});buttonMinus1.addEventListener("click",function(){if(inputCount1.value>=1){inputCount1.value=getCount1()-Number("1")}});let buttonPlus2=document.getElementById("count-plus-2");let buttonMinus2=document.getElementById("count-minus-2");let inputCount2=document.getElementById("counter-input-2")
function getCount2(){return Number(inputCount2.value)}
buttonPlus2.addEventListener("click",function(){if(inputCount2.value<=14){inputCount2.value=getCount2()+Number("1")}});buttonMinus2.addEventListener("click",function(){if(inputCount2.value>=1){inputCount2.value=getCount2()-Number("1")}});let buttonPlus3=document.getElementById("count-plus-3");let buttonMinus3=document.getElementById("count-minus-3");let inputCount3=document.getElementById("counter-input-3")
function getCount3(){return Number(inputCount3.value)}
buttonPlus3.addEventListener("click",function(){if(inputCount3.value<=14){inputCount3.value=getCount3()+Number("1")}});buttonMinus3.addEventListener("click",function(){if(inputCount3.value>=1){inputCount3.value=getCount3()-Number("1")}});let buttonPlus4=document.getElementById("count-plus-4");let buttonMinus4=document.getElementById("count-minus-4");let inputCount4=document.getElementById("counter-input-4")
function getCount4(){return Number(inputCount4.value)}
buttonPlus4.addEventListener("click",function(){if(inputCount4.value<=14){inputCount4.value=getCount4()+Number("1")}});buttonMinus4.addEventListener("click",function(){if(inputCount4.value>=1){inputCount4.value=getCount4()-Number("1")}});let buttonPlus5=document.getElementById("count-plus-5");let buttonMinus5=document.getElementById("count-minus-5");let inputCount5=document.getElementById("counter-input-5")
function getCount5(){return Number(inputCount5.value)}
buttonPlus5.addEventListener("click",function(){if(inputCount5.value<=14){inputCount5.value=getCount5()+Number("1")}});buttonMinus5.addEventListener("click",function(){if(inputCount5.value>=1){inputCount5.value=getCount5()-Number("1")}});let buttonPlus6=document.getElementById("count-plus-6");let buttonMinus6=document.getElementById("count-minus-6");let inputCount6=document.getElementById("counter-input-6")
function getCount6(){return Number(inputCount6.value)}
buttonPlus6.addEventListener("click",function(){if(inputCount6.value<=14){inputCount6.value=getCount6()+Number("1")}});buttonMinus6.addEventListener("click",function(){if(inputCount6.value>=1){inputCount6.value=getCount6()-Number("1")}});let buttonPlus7=document.getElementById("count-plus-7");let buttonMinus7=document.getElementById("count-minus-7");let inputCount7=document.getElementById("counter-input-7")
function getCount7(){return Number(inputCount7.value)}
buttonPlus7.addEventListener("click",function(){if(inputCount7.value<=14){inputCount7.value=getCount7()+Number("1")}});buttonMinus7.addEventListener("click",function(){if(inputCount7.value>=1){inputCount7.value=getCount7()-Number("1")}});let buttonPlus8=document.getElementById("count-plus-8");let buttonMinus8=document.getElementById("count-minus-8");let inputCount8=document.getElementById("counter-input-8")
function getCount8(){return Number(inputCount8.value)}
buttonPlus8.addEventListener("click",function(){if(inputCount8.value<=14){inputCount8.value=getCount8()+Number("1")}});buttonMinus8.addEventListener("click",function(){if(inputCount8.value>=1){inputCount8.value=getCount8()-Number("1")}});AOS.init({duration:1000,});window.onload = setTimeout(function () {document.getElementById('loader').style.display = 'none';}, 1500);